version: "3.3"

services:
  server:
    build:
      context: ./services/server
      dockerfile: Dockerfile
    volumes:
      - ./services/server:/usr/src/app
      - ./logs:/var/log/server_logs
    env_file:
      - .env.dev
    depends_on:
      - mongo-db
    ports:
      - "5000:5000"

  mongo-db:
    image: mongo
    ports:
      - "27017-27019:27017-27019"
    command:
      - "--auth"
      - "-f"
      - "/etc/mongod.conf"
    volumes:
      - ./services/database/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
      - ./services/database/mongo-volume:/data/db
      - ./services/database/mongod.conf:/etc/mongod.conf
      - ./logs:/var/log/mongodb
    env_file:
      - .env.dev
