version: "3.3"

services:
  test-server:
    build:
      context: ./services/server
      dockerfile: Dockerfile
    entrypoint: ./entrypoint.sh
    volumes:
      - ./services/tests/logs:/var/log/server_logs
      - ./initilize-server-data:/usr/src/app/initilize-server-data
    env_file:
      - .env.test
    depends_on:
      - test-mongo-db
    ports:
      - "${SERVER_PORT}:${SERVER_PORT}"

  test-mongo-db:
    image: mongo
    ports:
      - "${DB_PORT}:${DB_PORT}"
    command:
      - "--auth"
      - "-f"
      - "/etc/mongod.conf"
      - "--port"
      - "${DB_PORT}"
    volumes:
      - ./services/database/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
      - ./services/tests/mongo-volume:/data/db
      - ./services/database/mongod.conf:/etc/mongod.conf
      - ./services/tests/logs:/var/log/mongodb
    env_file:
      - .env.test

  test-suite:
    build:
      context: ./services/tests
      dockerfile: Dockerfile
    depends_on:
      - test-mongo-db
      - test-server
    entrypoint: ./entrypoint.sh
    volumes:
      - ./services/tests/logs:/usr/src/app/logs
      - ./initilize-server-data:/usr/src/app/initilize-server-data
    env_file:
      - .env.test
