version: "3.3"

services:
  server:
    build:
      context: ./services/server
      dockerfile: Dockerfile
    entrypoint: ./entrypoint.sh
    volumes:
      - ./services/server/src:/usr/src/app/src
      - ./logs:/var/log/server_logs
    env_file:
      - .env.dev
    depends_on:
      - mongo-db
    ports:
      - "${SERVER_PORT}:${SERVER_PORT}"

  nginx:
    build:
      context: ./services/website
      dockerfile: Dockerfile.dev
    volumes:
      - ./logs/nginx_logs:/var/log/nginx
      - ./services/website:/app
    ports:
      - "80:80"
    depends_on:
      - server

  mongo-db:
    image: mongo
    ports:
      - "${DB_PORT}:${DB_PORT}"
    command:
      - "--auth"
      - "-f"
      - "/etc/mongod.conf"
      - "--port"
      - "${DB_PORT}"
    volumes:
      - ./services/database/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
      - ./services/database/mongo-volume:/data/db
      - ./services/database/mongod.conf:/etc/mongod.conf
      - ./logs:/var/log/mongodb
    env_file:
      - .env.dev
